### ISSUE TITLE
mocha upgrade broke node 0.10, 0.12 testing

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#124]
due to ES6 code in `mocha@5` dependencies...

https://travis-ci.org/terser-js/terser/jobs/437200109#L2617

```
/home/travis/build/terser-js/terser/node_modules/mocha/node_modules/supports-color/index.js:2
const os = require('os');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/terser-js/terser/node_modules/mocha/lib/reporters/base.js:13:46)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Which may explain why `uglify-js` rolled their own mocha replacement.

**Comment by fabiosantoscode** [comment]
Ok. Back to mocha 3
