### ISSUE TITLE
Doesn't support parameter-less catch blocks

### ISSUE THREAD

**Issue by domenic** [terser-js/terser#127]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V`)**

terser 3.10.0

**Complete CLI command or `minify()` options used**

```
npx terser --compress --mangle --module base.mjs > base.min.mjs
```

**`terser` input**

```js
try {

} catch {

}
```

**`terser` output or error**

```
Parse error at base.mjs:3,8
} catch {
        ^
ERROR: Unexpected token punc «{», expected punc «(»
    at JS_Parse_Error.get (eval at <anonymous> (C:\Users\Domenic\AppData\Roaming\npm-cache\_npx\13528\node_modules\terser\tools\node.js:21:1), <anonymous>:75:23)
    at fatal (C:\Users\Domenic\AppData\Roaming\npm-cache\_npx\13528\node_modules\terser\bin\uglifyjs:318:53)
    at run (C:\Users\Domenic\AppData\Roaming\npm-cache\_npx\13528\node_modules\terser\bin\uglifyjs:257:9)
    at Object.<anonymous> (C:\Users\Domenic\AppData\Roaming\npm-cache\_npx\13528\node_modules\terser\bin\uglifyjs:185:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Expected result**

It treats it just like `catch (e) {}`. See https://tc39.github.io/ecma262/#sec-runtime-semantics-catchclauseevaluation

**Comment by kzc** [comment]
Calling an unimplemented new ES2019 feature a Terser bug is a stretch. Nevertheless, here's a working implementation that passes the test suite. It will probably have yet to be discovered `compress` or `mangle` bugs within catch blocks. Anyone interested in this feature can submit a PR.

```patch
diff --git a/lib/ast.js b/lib/ast.js
index 5c73b8c..ae804de 100644
--- a/lib/ast.js
+++ b/lib/ast.js
@@ -627,7 +627,7 @@ var AST_Catch = DEFNODE("Catch", "argname", {
     },
     _walk: function(visitor) {
         return visitor._visit(this, function() {
-            this.argname._walk(visitor);
+            if (this.argname) this.argname._walk(visitor);
             walk_body(this, visitor);
         });
     }
diff --git a/lib/compress.js b/lib/compress.js
index b9eb588..bb655f2 100644
--- a/lib/compress.js
+++ b/lib/compress.js
@@ -893,7 +893,7 @@ merge(Compressor.prototype, {
         var scope, i = 0;
         while (scope = compressor.parent(i++)) {
             if (scope instanceof AST_Scope) break;
-            if (scope instanceof AST_Catch) {
+            if (scope instanceof AST_Catch && scope.argname) {
                 scope = scope.argname.definition().scope;
                 break;
             }
@@ -4984,7 +4984,9 @@ merge(Compressor.prototype, {
                     }
                 }
                 if (scope instanceof AST_Catch) {
-                    block_scoped[scope.argname.name] = true;
+                    if (scope.argname) {
+                        block_scoped[scope.argname.name] = true;
+                    }
                 } else if (scope instanceof AST_IterationStatement) {
                     in_loop = [];
                 } else if (scope instanceof AST_SymbolRef) {
diff --git a/lib/output.js b/lib/output.js
index 9e77aa6..4cd27be 100644
--- a/lib/output.js
+++ b/lib/output.js
@@ -1320,10 +1320,12 @@ function OutputStream(options) {
     });
     DEFPRINT(AST_Catch, function(self, output) {
         output.print("catch");
-        output.space();
-        output.with_parens(function() {
-            self.argname.print(output);
-        });
+        if (self.argname) {
+            output.space();
+            output.with_parens(function() {
+                self.argname.print(output);
+            });
+        }
         output.space();
         print_braced(self, output);
     });
diff --git a/lib/parse.js b/lib/parse.js
index 8364b1d..1bbc40d 100644
--- a/lib/parse.js
+++ b/lib/parse.js
@@ -1847,9 +1847,13 @@ function parse($TEXT, options) {
         if (is("keyword", "catch")) {
             var start = S.token;
             next();
-            expect("(");
-            var name = parameter(undefined, AST_SymbolCatch);
-            expect(")");
+            if (is("punc", "{")) {
+                var name = null;
+            } else {
+                expect("(");
+                var name = parameter(undefined, AST_SymbolCatch);
+                expect(")");
+            }
             bcatch = new AST_Catch({
                 start   : start,
                 argname : name,
diff --git a/lib/transform.js b/lib/transform.js
index aacae2c..cdda1d5 100644
--- a/lib/transform.js
+++ b/lib/transform.js
@@ -152,7 +152,7 @@ TreeTransformer.prototype = new TreeWalker;
     });
 
     _(AST_Catch, function(self, tw) {
-        self.argname = self.argname.transform(tw);
+        if (self.argname) self.argname = self.argname.transform(tw);
         self.body = do_list(self.body, tw);
     });
 
diff --git a/test/compress/try-catch.js b/test/compress/try-catch.js
index 8b2751c..0864052 100644
--- a/test/compress/try-catch.js
+++ b/test/compress/try-catch.js
@@ -93,3 +93,16 @@ broken_safari_catch_scope_caveat: {
     expect_stdout: "PASS"
     node_version: ">=6"
 }
+
+parameterless_catch: {
+    input: {
+        try {
+            unknown();
+        } catch {
+            console.log("PASS");
+        }
+    }
+    expect_exact: 'try{unknown()}catch{console.log("PASS")}'
+    expect_stdout: "PASS"
+    node_version: ">=10"
+}
```
