### ISSUE TITLE
Keywords used as class functions clash when terser tries to deal with namespace imports (ES Module)

### ISSUE THREAD

**Issue by jdalrymple** [terser-js/terser#134]
**Bug report or Feature request?** 
Bug

**Version (complete output of `terser -V`)**
[ "rollup-plugin-terser": "^3.0.0", ( "terser": "^3.8.2")](https://github.com/TrySound/rollup-plugin-terser/blob/master/package.json)

(I didn't put this in the plugin repo because i think the problem originates from terser, not the plugin wrapper)

**Complete CLI command or `minify()` options used**
```
rollup -c
```
rollup.config

```javascript
import ts from 'rollup-plugin-typescript2';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import { terser } from "rollup-plugin-terser";
import typescript from 'typescript';
import pkg from './package.json';

 [ {
    input: 'src/index.ts',
    output: {
      file: pkg.module,
      format: 'es',
    },
    external: [...Object.keys(pkg.dependencies)],
    plugins: [
      ts({ typescript }),
      terser(),
    ],
  }]
```
**`terser` input**
```javascript
import * as Request from 'got';
import { get, stream, post, put, delete } from 'got';

var RequestHelper = /** @class */ (function () {
    function RequestHelper() {
    }
    RequestHelper.get = function (service, endpoint, options, _a) {
        if (options === void 0) { options = {}; }
        var _b = (_a === void 0 ? {} : _a).stream, stream$$1 = _b === void 0 ? false : _b;
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_c) {
                if (!stream$$1)
                    return [2 /*return*/, getPaginated(service, endpoint, options)];
                return [2 /*return*/, stream.apply(Request, defaultRequest(service, endpoint, {
                        query: options,
                    }))];
            });
        });
    };
    RequestHelper.post = function (service, endpoint, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, post.apply(Request, defaultRequest(service, endpoint, {
                            body: options,
                        }))];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, response.body];
                }
            });
        });
    };
    RequestHelper.put = function (service, endpoint, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, put.apply(Request, defaultRequest(service, endpoint, {
                            body: options,
                        }))];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, response.body];
                }
            });
        });
    };
    RequestHelper.delete = function (service, endpoint, options) {
        if (options === void 0) { options = {}; }
        return __awaiter(this, void 0, void 0, function () {
            var response;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, delete.apply(Request, 'test url')];
                    case 1:
                        response = _a.sent();
                        return [2 /*return*/, response.body];
                }
            });
        });
    };
    return RequestHelper;
}());
```

**`terser` output or error**
```
 216 |             return __generator(this, function (_a) {
  217 |                 switch (_a.label) {
> 218 |                     case 0: return [4 /*yield*/, delete.apply(Request,'test url' ))];
      |                                                       ^ Unexpected token: punc (.)
  219 |                     case 1:
[!] (terser plugin) Error: Unexpected token: punc (.)
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (/home/hyde/Projects/Libraries/node-gitlab/node_modules/terser/dist/bundle.js:65:27)
    at reportError (/home/hyde/Projects/Libraries/node-gitlab/node_modules/jest-worker/build/child.js:75:11)
    at execMethod (/home/hyde/Projects/Libraries/node-gitlab/node_modules/jest-worker/build/child.js:93:5)
    at process.on (/home/hyde/Projects/Libraries/node-gitlab/node_modules/jest-worker/build/child.js:40:7)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
**Expected result**
Not to error out on keywords on namespace imports, or provide some docs on how to handle this sort of problem :)

**Comment by Conduitry** [comment]
What's the code that Terser itself is actually getting? The error it's throwing is referring to something other than your original input code. It looks to me like the typescript plugin is returning invalid code.

**Comment by jdalrymple** [comment]
Hmm ill look deeper and update the issue!

**Comment by kzc** [comment]
This appears to be a Rollup issue, not Terser. If you remove `terser` from your Rollup config altogether and run the generated bundle through Acorn you'll see the same error reported.

Please follow the issue template in the future.

```
    Complete valid ECMAScript code exhibiting the issue with
    `terser` alone - without third party tools or libraries.
    Ideally the input should be as small as possible.
    Code must be in text form - not a screen cap.
    Post a link to a gist if necessary.

    Issues without a reproducible test case will be closed.
```

**Comment by jdalrymple** [comment]
When I remove terser from the config, I no longer get the error though :/

**Comment by kzc** [comment]
> run the generated bundle through Acorn you'll see the same error reported

You still have the error, but you are not aware of it.

**Comment by jdalrymple** [comment]
Ah, sorry I didnt pick up on that. Ill pass it onto rollup! Thank you!

**Comment by jdalrymple** [comment]
Just an update, error was due to me importing something incorrectly! I just didnt catch it until looking deeper.
