### ISSUE TITLE
bug: illegal escape codes in ES5 strings and template strings

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#135]
Details: https://github.com/terser-js/terser/issues/129#issuecomment-431609433

https://travis-ci.org/terser-js/terser/jobs/444146870#L5255-L5259
```
  1) Unicode Should not accept invalid unicode sequences:
     AssertionError [ERR_ASSERTION]: Missing expected exception (fail).
      at innerThrows (assert.js:646:7)
      at Function.throws (assert.js:662:3)
      at Context.<anonymous> (test/mocha/unicode.js:48:20)
```

Please revert 5ea6134 and reopen #129.

**Comment by fabiosantoscode** [comment]
Sorry about that. I think I went too fast
