### ISSUE TITLE
`npm test` errors - `multiprocess-map` breaks Node 0.10, 0.12, 6.

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#186]
**Bug report or Feature request?**

bug

`multiprocess-map` breaks Node 0.10, 0.12, 6.

ES6 code breaks Node 0.10 and Node 0.12.
`async` breaks Node 6.

**Version (complete output of `terser -V`)**

terser 3.11.0

**Issue**

Can the builds be rigged to only use `mocha` instead of `mochallel`?

https://travis-ci.org/terser-js/terser/builds/462500587?utm_source=github_status&utm_medium=notification

```
/home/travis/build/terser-js/terser/node_modules/multiprocess-map/lib/index.js:6
const multiprocessMap = async (values, fn, { max = defaultMax, processStdout = (x) => x } = { max: defaultMax, processStdout: (x) => x }) => {
                              ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/terser-js/terser/node_modules/mochallel/lib/index.js:20:11)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by kzc** [comment]
Patch above verified to work with `TRAVIS=1 npm test` on Node 0.10, 0.12 and 6.

**Comment by fabiosantoscode** [comment]
Thanks for the fix. I didn't think that multiprocess-map would cause an issue. I'll apply that soon enough.
