### ISSUE TITLE
unsafe is broken

### ISSUE THREAD

**Issue by thorn0** [terser-js/terser#192]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V`)**

terser 3.11.0

**Complete CLI command or `minify()` options used**
```console
> echo hasOwnProperty.call(a,b) | terser -c unsafe=true
ERROR: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AST_Dot.eval [as _eval] (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:10303:67)
    at AST_Dot.eval [as evaluate] (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:10091:28)
    at eval (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:14082:23)
    at AST_Dot.eval [as optimize] (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:7826:23)
    at Compressor.before (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:7809:24)
    at AST_Dot.eval [as transform] (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:4663:35)
    at eval (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:4785:43)
    at Compressor.before (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:7804:9)
    at AST_Call.eval [as transform] (eval at <anonymous> (D:\dev\node_modules\terser\tools\node.js:26:1), <anonymous>:4663:35)
```

**Comment by fabiosantoscode** [comment]
Thanks for reporting! I'll investigate this.

**Comment by fabiosantoscode** [comment]
The workaround would be to declare hasOwnProperty beforehand

**Comment by fabiosantoscode** [comment]
Fixed, releasing soon

**Comment by thorn0** [comment]
@fabiosantoscode  Still broken.
```console
d:\foo>echo hasOwnProperty.call(a.v,b) | terser -c unsafe=true
ERROR: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AST_Dot.return_false [as _eval] (d:\foo\node_modules\terser\lib\compress.js:2777:54)
    at AST_Dot._eval [as evaluate] (d:\foo\node_modules\terser\lib\compress.js:2555:28)
    at evaluate (d:\foo\node_modules\terser\lib\compress.js:6570:23)
    at AST_Dot.optimizer [as optimize] (d:\foo\node_modules\terser\lib\compress.js:281:23)
    at Rn.optimize [as before] (d:\foo\node_modules\terser\lib\compress.js:264:24)
    at AST_Dot.before [as transform] (d:\foo\node_modules\terser\lib\transform.js:61:35)
    at transform (d:\foo\node_modules\terser\lib\transform.js:183:43)
    at Rn.descend [as before] (d:\foo\node_modules\terser\lib\compress.js:259:9)
    at AST_Call.before [as transform] (d:\foo\node_modules\terser\lib\transform.js:61:35)

d:\foo>echo hasOwnProperty.apply(a,b) | terser -c unsafe=true
ERROR: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AST_Dot.return_false [as _eval] (d:\foo\node_modules\terser\lib\compress.js:2777:54)
    at AST_Dot._eval [as evaluate] (d:\foo\node_modules\terser\lib\compress.js:2555:28)
    at evaluate (d:\foo\node_modules\terser\lib\compress.js:6570:23)
    at AST_Dot.optimizer [as optimize] (d:\foo\node_modules\terser\lib\compress.js:281:23)
    at Rn.optimize [as before] (d:\foo\node_modules\terser\lib\compress.js:264:24)
    at AST_Dot.before [as transform] (d:\foo\node_modules\terser\lib\transform.js:61:35)
    at transform (d:\foo\node_modules\terser\lib\transform.js:183:43)
    at Rn.descend [as before] (d:\foo\node_modules\terser\lib\compress.js:259:9)
    at AST_Call.before [as transform] (d:\foo\node_modules\terser\lib\transform.js:61:35)

d:\foo>terser --version
terser 3.14.1
```
