### ISSUE TITLE
Mocha tests don't run

### ISSUE THREAD

**Issue by nifgraup** [terser-js/terser#211]
**Bug report or Feature request?**

Bug

**Version (complete output of `terser -V`)**

master build of terser 3fb9c49cdbe5d9c8c549cf859b0736e4c044965c, node.js v8.9.3

**Complete CLI command or `minify()` options used**

**`terser` input**

`$ node test/mocha.js`

**`terser` output or error**
```

arguments

net.js:701
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at WriteStream.Socket.write (net.js:701:11)
    at Socket.onData (/terser/node_modules/multiprocess-map/lib/index.js:131:46)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Expected result**

Mocha tests run. Note, everything fine with `$ TRAVIS=1 node test/mocha.js`.

**Comment by nifgraup** [comment]
fixed in #222
