### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by VikramTiwari** [terser-js/terser#229]
Seems similar to #120

Error trace
```
[1] ERROR in renderer.prod.js from Terser
[1] TypeError: Cannot read property 'name' of undefined
[1]     at name (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:2061:57)
[1]     at predicate (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:259:14)
[1]     at all (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:2065:22)
[1]     at join_object_assignments (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:2129:33)
[1]     at join_consecutive_vars (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:1080:17)
[1]     at tighten_body (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:3320:9)
[1]     at AST_BlockStatement.optimizer [as optimize] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:281:23)
[1]     at Rn.optimize [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:264:24)
[1]     at AST_BlockStatement.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
[1]     at transform (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:134:31)
[1]     at Rn.descend [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:259:9)
[1]     at AST_If.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
[1]     at transform (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:77:25)
[1]     at f (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:128:23)
[1]     at doit (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:153:52)
[1]     at MAP (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:76:16)
[1]     at do_list (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:178:25)
[1]     at Rn.descend [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:259:9)
[1]     at AST_Arrow.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
[1]     at transform (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:77:25)
[1]     at f (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:128:23)
[1]     at doit (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:153:52)
[1]     at MAP (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:76:16)
[1]     at do_list (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:184:21)
[1]     at Rn.descend [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:259:9)
[1]     at AST_Call.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
[1]     at transform (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:89:31)
[1]     at Rn.descend [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:259:9)
    at AST_SimpleStatement.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
[1]     at transform (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:77:25)
[1]     at f (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:128:23)
[1]     at doit (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/utils.js:153:52)
[1]     at MAP (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:76:16)
[1]     at do_list (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:178:25)
[1]     at Rn.descend [as before] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/compress.js:259:9)
[1]     at AST_Arrow.before [as transform] (/Users/vikram/Documents/code/omni/daeos-lite/node_modules/terser/lib/transform.js:61:35)
```

**Comment by fabiosantoscode** [comment]
Can you provide a reduced test case, in the minimal amount of javascript that will reproduce the issue?

**Comment by holsdjakne** [comment]
Hi,

I've hit the same error and produced a minimal test case:
```
var x = {};
var y = {...x};

// following line causes the error:
y.hello = 'world';
```

```
$ ./node_modules/.bin/terser --version
terser 3.14.1

$ ./node_modules/.bin/terser --mangle --compress -- ./test.js 
ERROR: Cannot read property 'name' of undefined
    at name (node_modules/terser/lib/compress.js:2063:37)
    at predicate (node_modules/terser/lib/utils.js:259:14)
    at all (node_modules/terser/lib/compress.js:2065:22)
    at join_object_assignments (node_modules/terser/lib/compress.js:2129:33)
    at join_consecutive_vars (node_modules/terser/lib/compress.js:1080:17)
    at tighten_body (node_modules/terser/lib/compress.js:3307:9)
    at AST_Toplevel.optimizer [as optimize] (node_modules/terser/lib/compress.js:281:23)
    at Rn.optimize [as before] (node_modules/terser/lib/compress.js:264:24)
    at AST_Toplevel.before [as transform] (node_modules/terser/lib/transform.js:61:35)
    at Rn.transform [as compress] (node_modules/terser/lib/compress.js:204:25)
```

Running terser without "--compress" works.

**Comment by fabiosantoscode** [comment]
Great, thanks! I'll isolate the option responsible for the error.

**Comment by hytromo** [comment]
I can reproduce the same error with terser v`3.16.1` in my project and using the above provided minimal test case.

There's more discussion about this here: <https://github.com/webpack/webpack/issues/8415>

**Comment by hytromo** [comment]
After testing things out more by running the terser tests, it seems that this line is the culprit: https://github.com/terser-js/terser/blob/master/lib/compress.js#L2198
```
return node.key.name != prop;
```
If it is changed into
```
return node.key && node.key.name != prop;
```
then the example code above compiles as it should **and all the terser tests run as well** (through `npm run test`). Though still I'm not confident with the codebase at all so as to submit a PR.

**Comment by fabiosantoscode** [comment]
@hytromo feel free to open a PR. I'm pretty confident in the test suite as it is, even if it we don't have functional tests (which I'll be adding sometime in the future). No breaking of the web should occur.
