### ISSUE TITLE
Terser overshadows parent function parameter while inlining function

### ISSUE THREAD

**Issue by Rafal2228** [terser-js/terser#241]
**Bug report**

Terser overshadows parent function argument with 'undefined' (var declaration) if the names of arguments are the same. In output code we can see it tries to access properties of object `o` which has just been declared with `var`.

**Version (complete output of `terser -V`)**

npx: installed 5 in 1.585s
terser 3.14.1
undefined

**Complete CLI command or `minify()` options used**

`npx terser ./min.js -c -o res.js`

**`terser` input**

```JavaScript
var a = {};

(function(global) {
  function fail(o) {
    var result = {};

    function inner() {
      return outer({
        one: o.one,
        two: o.two
      });
    }

    result.inner = function() {
      return inner();
    };

    return result;
  }

  function outer(o) {
    var ret;

    if (o) {
      ret = o.one;
    } else {
      ret = o.two;
    }

    return ret;
  }

  global.fail = fail;
})(a);

var b = a.fail({});
b.inner();
```

**`terser` output or error**
Output:
```JavaScript
var a = {};
!(function(global) {
  a.fail = function(o) {
    var result = {};
    return (
      (result.inner = function() {
        return (o = { one: o.one, two: o.two }) ? o.one : o.two;
        var o;
      }),
      result
    );
  };
})();
var b = a.fail({});
b.inner();
```
Error:
```
TypeError: Cannot read property 'one' of undefined
    at Object.result.inner (/home/rafal/res.js:1:170)
    at Object.<anonymous> (/home/rafal/res.js:1:235)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
**Expected result**

**Comment by fabiosantoscode** [comment]
My goodness, this looks like a hard bug. I'll try to check why this is happening but it will take a while.
