### ISSUE TITLE
global hasOwnProperty with unsafe=true is still broken

### ISSUE THREAD

**Issue by thorn0** [terser-js/terser#256]
**Bug report or Feature request?**

bug

Has been only partially fixed in #192.

**Version (complete output of `terser -V`)**

terser 3.16.1

**Complete CLI command or `minify()` options used**

```console
D:\foo>echo hasOwnProperty.call(a.v,b) | terser -c unsafe=true
ERROR: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AST_Dot.return_false [as _eval] (D:\foo\node_modules\terser\lib\compress.js:2912:54)
    at AST_Dot._eval [as evaluate] (D:\foo\node_modules\terser\lib\compress.js:2690:28)
    at evaluate (D:\foo\node_modules\terser\lib\compress.js:6721:23)
    at AST_Dot.optimizer [as optimize] (D:\foo\node_modules\terser\lib\compress.js:416:23)
    at Mn.optimize [as before] (D:\foo\node_modules\terser\lib\compress.js:399:24)
    at AST_Dot.before [as transform] (D:\foo\node_modules\terser\lib\transform.js:98:35)
    at transform (D:\foo\node_modules\terser\lib\transform.js:220:43)
    at Mn.descend [as before] (D:\foo\node_modules\terser\lib\compress.js:394:9)
    at AST_Call.before [as transform] (D:\foo\node_modules\terser\lib\transform.js:98:35)
```

**Comment by fabiosantoscode** [comment]
Thanks for reopening this. I haven't exactly been working on Terser a lot, as I have a new client.

I'm having a look right now.
