### ISSUE TITLE
mangle-properties regex cannot be tested if set by config file

### ISSUE THREAD

**Issue by AbcAeffchen** [terser-js/terser#316]
Bug

Version: terser 3.17.0

I use terser with options stored in a file. The files content is parsed as a JSON string. So it looks like this:

```
{
  "ecma": 6,
  "compress": {
    "unsafe": true,
    "unsafe_math": true
  },
  "mangle": {
    "toplevel": true,
    "properties": {
      "regex": "/^_/"
    }
  }
}
```
Now the Problem is, that one gets an error like this:

> ERROR: u.test is not a function
    at test (/usr/local/lib/node_modules/terser/lib/propmangle.js:236:29)
    at should_mangle (/usr/local/lib/node_modules/terser/lib/propmangle.js:246:14)
    at gn.add [as visit] (/usr/local/lib/node_modules/terser/lib/propmangle.js:185:17)
    at gn.visit [as _visit] (/usr/local/lib/node_modules/terser/lib/ast.js:1199:24)
    at AST_ObjectKeyVal._visit [as _walk] (/usr/local/lib/node_modules/terser/lib/ast.js:916:24)
    at AST_Object._walk (/usr/local/lib/node_modules/terser/lib/ast.js:903:31)
    at gn.call [as _visit] (/usr/local/lib/node_modules/terser/lib/ast.js:1203:21)
    at AST_Object._visit [as _walk] (/usr/local/lib/node_modules/terser/lib/ast.js:900:24)
    at AST_VarDef._walk (/usr/local/lib/node_modules/terser/lib/ast.js:748:40)
    at gn.call [as _visit] (/usr/local/lib/node_modules/terser/lib/ast.js:1203:21)

The reason is, that the regex is still a string when terser tries to use it.
But the regex string cannot be replaced by a regex literal because this cannot be parsed as JSON.

Maybe this holds also for the `keep_fname` option. The readme says that a regex literal is allowed here, but it seem to have no effect.

**Comment by L2jLiga** [comment]
There are two options how to fix this:

1. Parse given regular expression by other regex, like `/^\/.+\/[a-z]*$/` to create same regex with same flags
1. Accept [pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html) string as input and then call `new RegExp(regex)`

First solution will fix issue with given config
Second solution will require to change config "regex" field to `^_`

**Comment by AbcAeffchen** [comment]
I think the second option is the cleanest.

**Comment by L2jLiga** [comment]
Cool, I can do it later when will have access to laptop or you can do it yourself :)

RegExp constructor accepts RegExp literal or pattern string, hence we need to wrap right part into `new RegExp` here https://github.com/terser-js/terser/blob/cc00e783714c16b61288ec3233a6ca38b3de5cf6/lib/propmangle.js#L166

And update readme and typings to reflect changes.

Cheers

**Comment by AbcAeffchen** [comment]
Nice. I cannot do it before Monday. If you also have no time till then, I can do it.

**Comment by L2jLiga** [comment]
I'll create PR later today
