### ISSUE TITLE
from_mozilla_ast with function param default destructuring

### ISSUE THREAD

**Issue by mischnic** [terser-js/terser#358]
**Bug report or Feature request?**

Bug: `TypeError: y.definition is not a function`

**Version (complete output of `terser -V` or specific git commit)**

terser 4.0.0

**Complete CLI command or `minify()` options used**

```js
terser.minify(terser.AST_Node.from_mozilla_ast(acornAst), { warnings: true });
```

**`terser` input**

```js
function run({x} = {x: 2}){
  console.log(x);
}
```

API usage:

```js
const { parse: acornParse } = require("acorn");
const terser = require("terser");

const code = `
function run({x} = {x: 2}, a){
  console.log(x,a);
}
`;

const acornAst = acornParse(code, { locations: true });

const terserAst = terser.AST_Node.from_mozilla_ast(acornAst);
const output = terser.minify(terserAst, { warnings: true }); // doesn't work
const output2 = terser.minify(code, { warnings: true }); // works

console.log(output);
console.log(output2);
```

**`terser` output or error**

Using the acorn AST doesn't work. Calling terser with the source string works:
```
{ error:
   TypeError: y.definition is not a function
       at Dn.before (.../node_modules/terser/dist/bundle.min.js:1:166530)
       at AST_Defun.transform (.../node_modules/terser/dist/bundle.min.js:1:78697)
       at AST_Defun.drop_unused (.../node_modules/terser/dist/bundle.min.js:1:169136)
       at Fn.before (.../node_modules/terser/dist/bundle.min.js:1:119333)
       at AST_Defun.transform (.../node_modules/terser/dist/bundle.min.js:1:78697)
       at .../node_modules/terser/dist/bundle.min.js:1:78843
       at l (.../node_modules/terser/dist/bundle.min.js:1:1145)
       at e (.../node_modules/terser/dist/bundle.min.js:1:1465)
       at t (.../node_modules/terser/dist/bundle.min.js:1:78818)
       at .../node_modules/terser/dist/bundle.min.js:1:79020 }

{ code: 'function run({x:n}={x:2},o){console.log(n,o)}' }
```

**Expected result**
Parsing with acorn and running terser should behave the same as parsing the code with terser.

**Comment by mischnic** [comment]
This is the AST generated by `terser.parse` (no error minifying that):
```js
AST_Node {
  block_scope: undefined,
  body:
   [ AST_Node {
       block_scope: undefined,
       body: [],
       cname: undefined,
       enclosed: undefined,
       parent_scope: undefined,
       uses_eval: undefined,
       uses_with: undefined,
       functions: undefined,
       variables: undefined,
       async: false,
       is_generator: false,
       uses_arguments: undefined,
       argnames:
        [ AST_Node {
            right:
             AST_Node {
               properties:
                [ AST_Node {
                    value: AST_Node { literal: undefined, value: 2 },
                    key: 'x',
                    quote: undefined } ] },
            left:
             AST_Node {
               is_array: false,
               names:
                [ AST_Node {
                    value:
                     AST_Node {
                       thedef: undefined,
                       name: 'x',
                       scope: undefined,
                       init: undefined }, // --------- missing in `from_mozilla_ast`
                    key: 'x',
                    quote: undefined } ] },
            operator: '=' } ],
       name:
        AST_Node {
          thedef: undefined,
          name: 'run',
          scope: undefined,
          init: undefined },
       inlined: undefined } ],
  cname: undefined,
  enclosed: undefined,
  parent_scope: undefined,
  uses_eval: undefined,
  uses_with: undefined,
  functions: undefined,
  variables: undefined,
  globals: undefined }
```
The marked line is missing from the AST returned from `terser.AST_Node.from_mozilla_ast`

**Comment by L2jLiga** [comment]
I guess this stacktrace will be more usefull:

```
{ error:
   TypeError: sym.definition is not a function
       at TreeTransformer.before (.../node_modules/terser/lib/compress/index.js:3642:88)
       at AST_Defun.transform (.../node_modules/terser/lib/transform.js:98:35)
       at AST_Defun.drop_unused (.../node_modules/terser/lib/compress/index.js:3816:14)
       at Compressor.before (.../node_modules/terser/lib/compress/index.js:401:17)
       at AST_Defun.transform (.../node_modules/terser/lib/transform.js:98:35)
       at .../node_modules/terser/lib/transform.js:114:25
       at doit (.../node_modules/terser/lib/utils.js:138:23)
       at MAP (.../node_modules/terser/lib/utils.js:163:52)
       at do_list (.../node_modules/terser/lib/transform.js:113:16)
       at .../node_modules/terser/lib/transform.js:130:21 }
{ code: 'function run({x:n}={x:2},o){console.log(n,o)}' }
```

It seems like just adding check that `sym.definition` is not undefined solves issue.

**Comment by L2jLiga** [comment]
The difference is when we use `from_moz_ast` it defines default parameter assignment as AST_Binary instead of AST_DefaultAssignment
