### ISSUE TITLE
ERROR: Cannot read property '_walk' of null

### ISSUE THREAD

**Issue by benny0642** [terser-js/terser#417]
**Bug report**
It works fine at version 4.1.2, but got bug at 4.1.3.

**Version: 4.1.3**

**Complete CLI command or `minify()` options used**
`node_modules/.bin/terser javascript/test.js --config-file=terser.config.json -o javascript/test_compressed.js`

**`terser` input**

test.js: 

``` 
function BackgroundPosition(config) {
    var getBackgroundPosition = function (condition, weight) {
        var bodyClientHeight = document.body.clientHeight;
        var item1Height = 100;
        var backgroundDivision = (item1Height - bodyClientHeight) / 4;
        var backgroundOriginPosition = bodyClientHeight + backgroundDivision * weight;
        var backgroundEndPosition = 0;

        if (condition) {
            backgroundEndPosition = backgroundOriginPosition + backgroundDivision;
        }

        return [backgroundOriginPosition, backgroundEndPosition];
    };
    var backgroundPosition = getBackgroundPosition(config.condition, config.weight);
    this.background_origin_position = backgroundPosition[0];
    this.background_end_position = backgroundPosition[1];
}
```

terser.config.json:
```
{
  "compress": {
    "hoist_vars"       : false,
    "inline"           : 3
  },
  "output": {
    "ascii_only"       : true,
    "beautify"         : false,
    "indent_level"     : 0
  }
}
```

**`terser` output or error**

```
ERROR: Cannot read property '_walk' of null
    at AST_Binary._walk (/src/node_modules/terser/lib/ast.js:849:23)
    at mn.call [as _visit] (/src/node_modules/terser/lib/ast.js:1213:21)
    at AST_Binary._visit [as _walk] (/src/node_modules/terser/lib/ast.js:848:24)
    at AST_Binary._walk (/src/node_modules/terser/lib/ast.js:850:24)
    at mn.call [as _visit] (/src/node_modules/terser/lib/ast.js:1213:21)
    at AST_Binary._visit [as _walk] (/src/node_modules/terser/lib/ast.js:848:24)
    at AST_VarDef._walk (/src/node_modules/terser/lib/ast.js:747:40)
    at mn.call [as _visit] (/src/node_modules/terser/lib/ast.js:1213:21)
    at AST_VarDef._visit [as _walk] (/src/node_modules/terser/lib/ast.js:745:24)
    at AST_Var._walk (/src/node_modules/terser/lib/ast.js:655:32)
```

I do not get test_compressed.js

**Expected result**
generate test_compressed.js

**Comment by benny0642** [comment]
If I use inline:2, it works at 4.1.3. So I guess this issue could be realted to #120

**Comment by fabiosantoscode** [comment]
Slightly reduced test case:

```
function BackgroundPosition(config) {                                                 
    var getBackgroundPosition = function () {                                         
        var bodyClientHeight = window.bar;                                            
        var backgroundDivision = (100 - bodyClientHeight) / 4;                        
        var backgroundOriginPosition = bodyClientHeight + backgroundDivision * 123;   
        var backgroundEndPosition = 0;                                                
                                                                                      
        if (condition) {                                                              
            backgroundEndPosition = backgroundOriginPosition + backgroundDivision;    
        }                                                                             
                                                                                      
        return [backgroundOriginPosition];                                            
    };                                                                                
    var backgroundPosition = getBackgroundPosition(null, null);                       
}                                                                                     
```

**Comment by tyscorp** [comment]
```js
function test() {
  var fn = function () {
    var a = Math.random();
    var b = a + 1;
    var c = a + b + 1;
    var d = c + b;

    return c;
  };
  var x = fn();
}
```

**Comment by fabiosantoscode** [comment]
Fixed in 4.1.4

**Comment by L2jLiga** [comment]
@fabiosantoscode should this issue be closed?

**Comment by fabiosantoscode** [comment]
Yes, thank you :)

**Comment by benny0642** [comment]
terser@4.1.4 works for me. Thank you guys.
