### ISSUE TITLE
numerous ES6+ spidermonkey AST parse and output bugs

### ISSUE THREAD

**Issue by kzc** [terser-js/terser#42]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V`)**

latest master (post terser 3.7.5)

**Complete CLI command or `minify()` options used**

This works:

```
$ bin/uglifyjs test/input/spidermonkey/input.js --module -p acorn -m 
import"mod-name";import Foo from"bar";import*as Food from"food";import{Bar,Baz}from"lel";import Bar1,{Foo2}from"lel";import{Bar2 as kex,Baz as food}from"lel";const t=1;let o=6;export default t;export const z=4;export function fun(){}export*from"a.js";export{A}from"a.js";export{A1,B1}from"a.js";export{C};(t,[b],{c:n=3},...d)=>null;()=>{};async function r(){}function*a(){yield 1;yield*2}class e extends Object{constructor(...args){super.init(args)}foo(){}}t=class{static staticMethod(){}static get foo(){}static set bar(t){}get x(){}set x(t){}static(){}get(){}async set(){}*bar(){}static*baz(){}*["constructor"](){}static["constructor"](){}[z](){}"%"(){}};o={get x(){},set x(t){},bar(){},*bar(){},*["constructor"](){}};function r(){console.log(new.target)}console.log([10,...[],20,...[30,40],50]["length"]);var{w:w1,...V}={w:7,x:1,y:2};for(const t of o){}async function s(){await t}``;`x`;`x${1}`;String.raw`\n`;var n=([])=>"foo";var i=({})=>"bar";var f=(n="default")=>n;var l=({foo:n="default",bar:baz="default"})=>n;var v=(...[n])=>n;var v=(...{foo:n})=>n;var x=({[compute()]:t})=>{};var g=([,,...t]=[1,2])=>{};var u=({foo:n})=>{};var m=(...[])=>"foo";var p=(...{})=>"foo";async t=>await t;var[aa,bb]=cc;var[aa,[bb,cc]]=dd;var[,[,,,,,],,,zz]=xx;var[,,zzz,,]=xxx;var{aa:aa,bb:bb}={aa:1,bb:2};var{aa:aa,bb:{cc:cc,dd:dd}}={aa:1,bb:{cc:2,dd:3}};for(const[t,o]in pairs);for(const[z]=0;;);for(const{c:c}of cees);var z={get:get,set:"foo",get bar(){return this.get},get 5(){return"five"},get 3925(){return"f five five"},get five(){return 5},set one(t){this._one=t},set 9(t){this._nine=t},set 10(t){this._ten=t},set eleven(t){this._eleven=t},*"%"(){return 2},*["%"](){return 2},[z](){}};console.log(/rx/gi.test("RX"));/rx1/;/\/rx2\//gi;/\\rx3\\/gi;/[\\/]/gi;/[\\/]/;
```

This doesn't work:
```
$ bin/uglifyjs test/input/spidermonkey/input.js --module -p acorn -m -c
ERROR: sym.definition is not a function
```

Here's at least one of the issues:
```
$ echo 'function f({foo = 12} = {}){ console.log(foo); } f({}); f({foo: 34});' | node
12
34
```
```
$ echo 'function f({foo = 12} = {}){ console.log(foo); } f({}); f({foo: 34});' | bin/uglifyjs -p acorn
function f({foo:foo=12}={}){console.log(foo)}f({});f({foo:34});
```
```
$ echo 'function f({foo = 12} = {}){ console.log(foo); } f({}); f({foo: 34});' | bin/uglifyjs -p acorn -c
ERROR: sym.definition is not a function
```
@fabiosantoscode Would you mind taking a look at it when you have the time?

**Comment by kzc** [comment]
I see what's going on... the wrong `terser` AST node types are being created in `lib/mozilla-ast.js`:

```
$ cat ex.js 
function f({foo = 12} = {}){ console.log(foo); } f({}); f({foo: 34});
```
```
$ cat ex.js | bin/uglifyjs -o ast > correct-ast.json
```
```
$ cat ex.js | bin/uglifyjs -p acorn -o ast > spider-ast.json
```
```diff
$ diff -u correct-ast.json spider-ast.json 
--- correct-ast.json	2018-05-22 17:25:40.000000000 -0400
+++ spider-ast.json	2018-05-22 17:26:00.000000000 -0400
@@ -1,6 +1,7 @@
 {
   "_class": "AST_Toplevel",
   "globals": [
+    "1000003 foo",
     "1000004 console"
   ],
   "variables": [
@@ -10,6 +11,7 @@
     "1000002 f"
   ],
   "enclosed": [
+    "1000003 foo",
     "1000004 console",
     "1000002 f"
   ],
@@ -23,7 +25,7 @@
       },
       "argnames": [
         {
-          "_class": "AST_DefaultAssign",
+          "_class": "AST_Binary",
           "operator": "=",
           "left": {
             "_class": "AST_Destructuring",
@@ -32,10 +34,10 @@
                 "_class": "AST_ObjectKeyVal",
                 "key": "foo",
                 "value": {
-                  "_class": "AST_DefaultAssign",
+                  "_class": "AST_Binary",
                   "operator": "=",
                   "left": {
-                    "_class": "AST_SymbolFunarg",
+                    "_class": "AST_SymbolRef",
                     "name": "foo",
                     "thedef": "1000003 foo"
                   },
@@ -58,8 +60,7 @@
       "is_generator": false,
       "async": false,
       "variables": [
-        "1000001 arguments",
-        "1000003 foo"
+        "1000001 arguments"
       ],
       "enclosed": [
         "1000003 foo",
```

If the same `terser` `-o ast``diff` technique is used for `test/input/spidermonkey/input.js` you'll see problems with:

* AST_Import
* AST_SymbolImport
* `imported_name` vs `imported_names`
* AST_SymbolImportForeign
* AST_SymbolConst
* AST_SymbolLet
* exported_names
* exported_definition
* AST_SymbolExportForeign
* AST_SymbolExport
* AST_Destructuring
* AST_SymbolRef used instead of AST_SymbolFunarg
* AST_Binary used instead of AST_DefaultAssign
* AST_Function used instead of AST_Accessor
* `arguments` "ownership" in AST_Arrow vs regular functions
* AST_Super missing a `name` property with value `"super"`
* AST_This missing a `name` property with value `"this"`
* incorrect `is_generator` use

Possible issues:

* using numeric values for the `name` property of AST_SymbolMethod instead of string literal
* empty `body` for AST_Arrow functions
* `raw_source` still wrong in `AST_RegExp` - but no longer used in `lib/compress.js` and `lib/output.js`, but might matter to other ESTree parsers and/or generators.

Likely non-issues:

* missing `quote` property value
* differing `thedef` property values - probably a symptom of incorrect AST type use above
* `variables` vs `enclosed` (probably a secondary effect of `figure_out_scope` due to wrong AST classes

There ought to be a relatively simple way to rig `test/run-tests.js` to compare the `terser` AST generated by `lib/parser.js` to the `terser` AST created via `acorn` + `spidermonkey` parse.

**Comment by Qix-** [comment]
I'm seeing this too.

```
TypeError: Cannot read property 'figure_out_scope' of null
    at Compressor.compress (eval at <anonymous> (/src/node_modules/terser/tools/node.js:21:1), <anonymous>:7715:18)
    at Object.minify (eval at <anonymous> (/src/node_modules/terser/tools/node.js:21:1), <anonymous>:15829:75)
    at Object.exec (/src/lib/builtin/js/minify.js:27:25)
    at timedSection (/src/lib/pipeline.js:132:59)
    at timedSection (/src/lib/util/timed-section.js:22:24)
    at executePipeline (/src/lib/pipeline.js:132:25)
    at Pipeline.execute (/src/lib/pipeline.js:155:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
